name: Docker Workflow

on:
  - push
  
jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Build 
      run: docker build -t humble15/jeremiah-aidoo-github-actions:latest .

    - name: Docker Login
      run: docker login --username=humble15 --password=Humble@1997

    - name: Docker Publish 
      run: docker push humble15/jeremiah-aidoo-github-actions:latest

  docker_deploy:
    needs: docker_build
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Docker Login
        run: docker login --username=humble15 --password=Humble@1997
      - name: Docker Run
        run: docker run -d -p 8080:80 humble15/jeremiah-aidoo-github-actions:latest
